config/routes.rb
Rails.application.routes.draw do
  resources :reglements
  resources :actes
  resources :type_paiments
  resources :ipms
  resources :comptabilites do
    member do
      get :print_button
    end
  end
  devise_for :users, path: ''
  #devise_for :users, path: '', path_names: {sign_in: 'Login', sign_out: 'Logout', sign_up: 'Register'}, controllers:{sessions: 'users/sessions'}
  get 'pages/index'
  resources :caisses

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'pages#index'
end

app/models/comptabilite.rb
class Comptabilite < ApplicationRecord
  belongs_to :ipm, optional: true
  belongs_to :type_paiment, optional: true
  belongs_to :acte

  has_many :reglement_mensuel

  validates_presence_of :nom, :prenom, :acte_id, :montant, :telephone, :type_paiment_id

  
  def self.bilan_journalier(select_date)
    @selected_date = select_date
# This will look for records on the given date between 00:00:00 and 23:59:59
    @caiss_journaliers = Comptabilite.where(:created_at => @selected_date.beginning_of_day..@selected_date.end_of_day)
  end
  
  def self.bilan_mensuel(select_date)
    @selected_date = select_date
    @caiss_mensuel = Comptabilite.where(:created_at => @selected_date.beginning_of_month..@selected_date.end_of_month)
  end


  def self.recherche_caiss_journalier(select_date)
    @selected_date = select_date
# This will look for records on the given date between 00:00:00 and 23:59:59
    @caiss_journaliers = Comptabilite.where(:created_at => @selected_date.beginning_of_day..@selected_date.end_of_day)
  end

  def self.recent
    order("created_at DESC")
  end
end

app/controllers/comptabilites_controller.rb
class ComptabilitesController < ApplicationController
  before_action :set_comptabilite, only: %i[ show edit update destroy ]

  access user: {except: [:index, :edit, :show, :update, :create, :new, :destroy]}, editor:[:new, :create, :update, :edit, :show, {except: [:index, :destroy]}], admin: :all, directeur: :all
  # GET /comptabilites or /comptabilites.json
  def index
    if !logged_in?(:admin, :directeur)
      redirect_to root_path(), notice: "Vous n'êtes pas autorisé à acceder à cette page"
    else
      @date_day = params[:selected_date_day]
      @date_month = params[:selected_date_month]
      @comptabilites = Comptabilite.all.recent

      @caiss_journalier = Comptabilite.bilan_journalier(Date.today)
      
      if @date_month && !@date_month.empty?
        @date_convert = @date_month.to_date

        @c_mensuel = Comptabilite.bilan_mensuel(@date_convert)
        @comptabilite_mensuel = @c_mensuel.sum("montant")
        
        @reglmnt_mensuel = Reglement.bilan_mensuel(@date_convert)
        @reglement_mensuel = @reglmnt_mensuel.sum("montant")

        @bilan_mensuel = @comptabilite_mensuel + @reglement_mensuel
        
        @date_month_info = @date_month.to_datetime
      end

      if @date_day && !@date_day.empty?
        @date_convert = @date_day.to_date
        @recherche_caiss_journalier = Comptabilite.recherche_caiss_journalier(@date_convert)
      end
      @c_total = Comptabilite.all.sum("montant")
    
    end
    
  end

  # GET /comptabilites/1 or /comptabilites/1.json
  def show
    respond_to do |format|
      format.html
      format.pdf do
          render pdf: "Ticket No. #{@comptabilite.id}",
          page_size: 'A7',
          template: "comptabilites/show.html.erb",
          layout: "pdf.html",
          orientation: "Landscape",
          lowquality: true,
          zoom: 1,
          dpi: 75
      end
    end
  end

  # GET /comptabilites/new
  def new
    @comptabilite = Comptabilite.new

  end

  # GET /comptabilites/1/edit
  def edit
  end

  # POST /comptabilites or /comptabilites.json
  def create
    @comptabilite = Comptabilite.new(comptabilite_params)

    if (@comptabilite.type_paiment_id == "" || @comptabilite.pourcentage_ipm == "" || @comptabilite.ipm_id == "" || @comptabilite.montant == "" || @comptabilite.montant_total == "" || @comptabilite.nom == "" || @comptabilite.prenom == "" || @comptabilite.acte_id == "")
      if !@comptabilite.save
          respond_to do |format|
            format.html { render :new, status: :unprocessable_entity }
            format.json { render json: @comptabilite.errors, status: :unprocessable_entity }
        end
      end
    else
      respond_to do |format|
        if @comptabilite.type_paiment_id == 1
          if (@comptabilite.pourcentage_ipm!= "" || @comptabilite.ipm_id != "" || @comptabilite.montant_total != "" || @comptabilite.montant < 0)
            format.html { render :new}         
            @msg_error = "ECHEC D'ENREGISTREMENT. VOUS AVEZ CHOISI CASH COMME TYPE DE PAIMENT DONC VIDER LE LISTE IPM AINSI QUE LE POURCENTAGE DE L'IPM."
          else
            if @comptabilite.save
              format.html { redirect_to @comptabilite, notice: "Enregistrer avec succés." }
              format.json { render :show, status: :created, location: @comptabilite }
            else
              format.html { render :new, status: :unprocessable_entity }
              format.json { render json: @comptabilite.errors, status: :unprocessable_entity }
            end
          end 
        elsif @comptabilite.type_paiment_id == 2
          if (@comptabilite.pourcentage_ipm == "" || @comptabilite.pourcentage_ipm < 0 || @comptabilite.ipm_id == "" || @comptabilite.montant == "" || @comptabilite.montant < 0 || @comptabilite.montant_total <= 0 || @comptabilite.montant_total == "" )
            format.html { render :new}         
            @msg_error = "ECHEC D'ENREGISTREMENT. VOUS AVEZ CHOISI IPM COMME TYPE DE PAIMENT DONC VEUILLEZ SELECTIONNER DANS LA LISTE DES IPM ET SAISIR LE POURCENTAGE DE PRISE EN CHARGE.LE MONTANT DOIT PAS ÊTRE INFÉRIEUR À 0"
          elsif (@comptabilite.pourcentage_ipm == 100 && @comptabilite.montant != 0)
            format.html { render :new}         
            @msg_error = "ECHEC D'ENREGISTREMENT.  LE POURCENTAGE DE PRISE EN CHARGE ET LE MONTANT SAISI NE CORRESPONDENT PAS."
          elsif (@comptabilite.pourcentage_ipm < 100 && @comptabilite.montant <= 0)
            format.html { render :new}         
            @msg_error = "ECHEC D'ENREGISTREMENT.  LE POURCENTAGE DE PRISE EN CHARGE ET LE MONTANT SAISI NE CORRESPONDENT PAS."
          elsif (@comptabilite.pourcentage_ipm == 0 && @comptabilite.montant == 0)
            format.html { render :new}         
            @msg_error = "ECHEC D'ENREGISTREMENT.  LE POURCENTAGE DE PRISE EN CHARGE ET LE MONTANT SAISI NE CORRESPONDENT PAS."
          else
            if @comptabilite.save
              format.html { redirect_to @comptabilite, notice: "Enregistrer avec succés." }
              format.json { render :show, status: :created, location: @comptabilite }
            else
              format.html { render :new, status: :unprocessable_entity }
              format.json { render json: @comptabilite.errors, status: :unprocessable_entity }
            end
          end
        end
      end
    end
  end

  # PATCH/PUT /comptabilites/1 or /comptabilites/1.json
  def update
    type_paiment = params[:comptabilite][:type_paiment_id]
    param_type_paiment = params[:comptabilite][:type_paiment_id].to_i

    pourcentage_ipm = params[:comptabilite][:pourcentage_ipm]
    param_pourcentage_ipm = params[:comptabilite][:pourcentage_ipm].to_i

    ipm_id = params[:comptabilite][:ipm_id]
    param_ipm_id = params[:comptabilite][:ipm_id].to_i

    montant = params[:comptabilite][:montant]
    param_montant = params[:comptabilite][:montant].to_i

    montant_total = params[:comptabilite][:montant_total]
    param_montant_total = params[:comptabilite][:montant_total].to_i

    respond_to do |format|
      if type_paiment == "1"
        if (pourcentage_ipm != "" || ipm_id != "" || montant_total != "" || param_montant <= 0)
          format.html { render :edit}         
          @msg_error = "ECHEC D'ENREGISTREMENT. VOUS AVEZ CHOISI CASH COMME TYPE DE PAIMENT DONC VIDER LE LISTE IPM AINSI QUE LE POURCENTAGE DE L'IPM." 
        else
          if @comptabilite.update(comptabilite_params)
            format.html { redirect_to @comptabilite, notice: "Modifier avec succés." }
            format.json { render :show, status: :ok, location: @comptabilite }
          else
            format.html { render :edit, status: :unprocessable_entity }
            format.json { render json: @comptabilite.errors, status: :unprocessable_entity }
          end
        end
      elsif type_paiment == "2"
        if (pourcentage_ipm == "" || ipm_id == "" || montant == "" || param_montant < 0 || montant_total == "" || param_montant_total <= 0)
          format.html { render :edit}         
          @msg_error = "ECHEC D'ENREGISTREMENT. VOUS AVEZ CHOISI IPM COMME TYPE DE PAIMENT DONC VEUILLEZ SELECTIONNER DANS LA LISTE DES IPM ET SAISIR LE POURCENTAGE DE PRISE EN CHARGE.LE MONTANT DOIT PAS ÊTRE INFÉRIEUR À 0"
        elsif (param_pourcentage_ipm < 100 && (param_montant <= 0 || montant == ""))
          format.html { render :edit}         
          @msg_error = "ECHEC D'ENREGISTREMENT.  LE POURCENTAGE DE PRISE EN CHARGE NE CORRESPOND PAS AVEC LE MONTANT SAISI."
        elsif (param_pourcentage_ipm == 100 && (param_montant > 0 || param_montant < 0 ))
          format.html { render :edit}         
          @msg_error = "ECHEC D'ENREGISTREMENT.  LE POURCENTAGE DE PRISE EN CHARGE ET LE MONTANT SAISI NE CORRESPONDENT PAS."
        else
          if @comptabilite.update(comptabilite_params)
            format.html { redirect_to @comptabilite, notice: "Modifier avec succés." }
            format.json { render :show, status: :ok, location: @comptabilite }
          else
            format.html { render :edit, status: :unprocessable_entity }
            format.json { render json: @comptabilite.errors, status: :unprocessable_entity }
          end
        end
      end
    end
  end

  # DELETE /comptabilites/1 or /comptabilites/1.json
  def destroy
    @comptabilite.destroy
    respond_to do |format|
      format.html { redirect_to comptabilites_url, notice: "Comptabilite was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comptabilite
      @comptabilite = Comptabilite.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def comptabilite_params
      params.require(:comptabilite).permit(:nom, :prenom, :acte_id, :montant, :montant_total, :telephone, :selected_date_day, :selected_date_month, :ipm_id, :type_paiment_id, :pourcentage_ipm)
    end

    #def set_recherch_comptabilite_params
    #  select_date = params[:selected_date] if !params[:selected_date]#.nil?
    #end
end

app/helpers/comptabilites_helper.rb
module ComptabilitesHelper
end

app/views/comptabilites/_form.html.erb
<div class="container portfolio-container">
  <%= form_with(model: comptabilite, local: true) do |form| %>
    <% if comptabilite.errors.any? %>
      <div id="error_explanation" class="alert alert-danger">
        <h2>Impossible d'enregistrer: <%= pluralize(comptabilite.errors.count, "erreur") %></h2>

        <ul>
        <% comptabilite.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
  <% if @msg_error %>
    <div class="alert alert-danger">
    <ul>
      <li><%= @msg_error %></div></li>
    </ul>
  <% end %>
    <div class="form-group col-md-4">
      <%= form.label :nom %>
      <%= form.text_field :nom, class:"form-control" %>
    </div>

    <div class="form-group col-md-4">
      <%= form.label :prenom %>
      <%= form.text_field :prenom, class:"form-control" %>
    </div>

    <div class="form-group col-md-4">
      <%= form.label :acte %>
      <%= form.collection_select(:acte_id, Acte.all, :id, :name,
        {
          include_blank: true
        },
        class: 'form-control',
      ) 
    %>
    </div>

    <div class="form-group  col-md-4">
    <%= form.label :type_paiment_id %>
    <%= form.collection_select(:type_paiment_id, TypePaiment.all, :id, :name,
        {
          #selected: "Choisir un IPM",
          include_blank: true
        },
        onchange: 'getIDTypePaiment()',
        class: 'form-control'
      ) 
    %>
    </div>

    <div id="ipm">
      <div class="form-group col-md-4">
        <%= form.label :ipm_id %>
        <%= form.collection_select(:ipm_id, Ipm.all, :id, :name,
            {
              include_blank: true
            },
            class: 'form-control'
          ) 
        %>
      </div>

      <div class="form-group col-md-4">
        <%= form.label :montant_total %>
        <%= form.number_field :montant_total, min: 0, class:"form-control" %>
      </div>
      
      <div class="form-group col-md-4">
        <%= form.label :pourcentage_ipm %>
        <%= form.number_field :pourcentage_ipm, min: 0, max: 100, class:"form-control" %>
      </div>
    </div>



    <div class="form-group col-md-4" style="" id="montant">
      <%= form.label :montant %>
      <%= form.number_field :montant, class:"form-control", min: 0 %>
    </div>

    <div class="form-group col-md-4">
      <%= form.label :telephone %>
      <%= form.text_field :telephone, class:"form-control" %>
    </div>
    

    <br>
    <div class="form-group">
      <%= form.submit "Enregistrer", class:"btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/comptabilites/edit.html.erb
<div class="container portfolio-container">
  <h1>Modifer Caisse</h1>

  <%= render 'form', comptabilite: @comptabilite %>

  <%= link_to 'Voir', @comptabilite %> |
  <%= link_to 'Retour', comptabilites_path %>
</div>

app/views/comptabilites/index.html.erb
<div class="container portfolio-container">
  <p id="notice"><%= notice %></p>
  <%= link_to 'Nouveau', new_comptabilite_path, class:"btn btn-primary" %> <%= link_to 'Réglement', reglements_path(), class:"btn btn-outline-dark" %>
  <br>
<hr>
  <div class="row">
    <div class="col-md-4">
      <%= form_tag(comptabilites_path, method: :get) do %>
        <div class="form-group">
          <%= date_field_tag(:selected_date_day, params[:selected_date_day], class:"form-control") %>
          <hr class="">
        <%= submit_tag ("Bilan du jour"),  class:"form-control btn-primary" %>
        </div>
        <br>
        
      <% end %>
    </div>

    <div class="col-md-4">
      <%= form_tag(comptabilites_path, method: :get) do %>
        <div class="form-group">
          <%= date_field_tag(:selected_date_month, params[:selected_date_month], class:"form-control") %>
        </div>
        <hr class="">
        <div class="form-group">
        <%= submit_tag ("Bilan du mois"),  class:"form-control btn-primary" %>
        </div>        
      <% end %>
    </div>
  </div>
  <% if @date_month && @date_month != "" %>
    <span class="alert alert-primary d-flex align-items-center" role="alert">Le bilan du <%= @date_month_info.strftime("%Y/%m") if !@date_month.empty? %> est de :<%= @bilan_mensuel if @bilan_mensuel %>F</span>
  <% end %>

  <% if @date_day && @date_day != "" %>
    <span class="alert alert-primary d-flex align-items-center" role="alert">Le bilan du <%= @date_day %> est de :<%= @recherche_caiss_journalier.sum("montant") if @recherche_caiss_journalier %>F</span>
  <% end %>
  <hr>
  <h1>Encaissé <span> Aujourd'hui: <%= @total= @caiss_journalier.sum("montant") %> </span -->
  <br></h1>
  <div class="table-responsive">
    <table class="table">
      <thead>
        <tr>
          <th>Nom</th>
          <th>Prenom</th>
          <th>Acte</th>
          <th>Type Paiement</th>
          <th>Pourcentage IPM</th>
          <th>Montant</th>
          <th>Date :</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @comptabilites.each do |comptabilite| %>
          <tr>
            <td><%= comptabilite.nom %></td>
            <td><%= comptabilite.prenom %></td>
            <td><%= comptabilite.acte.name %></td>
            <td><%= comptabilite.type_paiment.name %></td>
            <td><%= "#{comptabilite.pourcentage_ipm} %" if comptabilite.pourcentage_ipm %></td>
            <td><%= comptabilite.montant %></td>
            <td><%= comptabilite.created_at %></td>
            <td><%= link_to 'Voir', comptabilite,class:"btn btn-warning" %></td>

            <td><%= link_to 'Modifier', edit_comptabilite_path(comptabilite),class:"btn btn-info" %></td>

            <td><%= link_to 'Supprimer', comptabilite, method: :delete, data: { confirm: 'Êtes-vous sûre?' },class:"btn btn-danger" %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  
</div>

app/views/comptabilites/new.html.erb
<div class="container portfolio-container">
  <h1>Nouveau Encaissement</h1>

  <%= render 'form', comptabilite: @comptabilite %>

  <%= link_to 'Retour', comptabilites_path %>
</div>

app/views/comptabilites/show.html.erb
<div class="container portfolio-container">
  <% if notice %>
    <p id="notice" class="alert alert-success"><%= notice %></p>
  <% end %>
<%= link_to "Print Ticket", comptabilite_path(@comptabilite, format: :pdf, target: "_blank") %>
  <p>
    <strong><h1>Nom:</h1></strong>
    <span style=""><h4><%= @comptabilite.nom %></h4></span>
  </p>

  <p>
    <strong><h1>Prenom:</h1></strong>
    <span style=""><h4><%= @comptabilite.prenom %></h4></span>
  </p>

  <p>
    <strong><h1>Acte:</h1></strong>
    <span style=""><h4><%= @comptabilite.acte.name %></h4></span>
  </p>

  <p>
    <strong><h1>Type de Paiement:</h1></strong>
    <span style=""><h4><%= @comptabilite.type_paiment.name %></h4></span>
  </p>

  <% if !@comptabilite.ipm.nil?%>
    <p>
      <strong><h1>Nom IPM:</strong>
      <span style=""><h4><%= @comptabilite.ipm.name %></h4></span>
    </p>

    <p>
      <strong><h1>Le montant total:</strong>
      <span style=""><h4><%= @comptabilite.montant_total %></h4></span>
    </p>

    <p>
      <strong><h1>Pourcentage de prise en charge:</strong>
      <span style=""><h4><%= @comptabilite.pourcentage_ipm %>%</h4></span>
    </p>
  <% end %>
  <p>
    <strong><h1>Montant:</strong>
    <span style=""><h4><%= @comptabilite.montant %></h4></span>
  </p>

  <p>
    <strong><h1>Telephone:</h1></strong>
    <span style=""><h4><%= @comptabilite.telephone %></h4></span>
  </p>

  <%= link_to 'Modifer', edit_comptabilite_path(@comptabilite) %> |
  <%= link_to 'Retour', comptabilites_path %>
</div>