config/routes.rb
Rails.application.routes.draw do
  resources :reglements
  resources :actes
  resources :type_paiments
  resources :ipms
  resources :comptabilites do
    member do
      get :print_button
    end
  end
  devise_for :users, path: ''
  #devise_for :users, path: '', path_names: {sign_in: 'Login', sign_out: 'Logout', sign_up: 'Register'}, controllers:{sessions: 'users/sessions'}
  get 'pages/index'
  resources :caisses

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'pages#index'
end

app/models/type_paiment.rb
class TypePaiment < ApplicationRecord
  has_many :comptabilites
end

app/controllers/type_paiments_controller.rb
class TypePaimentsController < ApplicationController
  before_action :set_type_paiment, only: [:show, :edit, :update, :destroy]
  access all: [:index, :show, :new, :edit, :create, :update, :destroy], user: :all

  # GET /type_paiments
  def index
    @type_paiments = TypePaiment.all
  end

  # GET /type_paiments/1
  def show
  end

  # GET /type_paiments/new
  def new
    @type_paiment = TypePaiment.new
  end

  # GET /type_paiments/1/edit
  def edit
  end

  # POST /type_paiments
  def create
    @type_paiment = TypePaiment.new(type_paiment_params)

    if @type_paiment.save
      redirect_to @type_paiment, notice: 'Type paiment was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /type_paiments/1
  def update
    if @type_paiment.update(type_paiment_params)
      redirect_to @type_paiment, notice: 'Type paiment was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /type_paiments/1
  def destroy
    @type_paiment.destroy
    redirect_to type_paiments_url, notice: 'Type paiment was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_type_paiment
      @type_paiment = TypePaiment.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def type_paiment_params
      params.require(:type_paiment).permit(:name)
    end
end

app/helpers/type_paiments_helper.rb
module TypePaimentsHelper
end

app/views/type_paiments/_form.html.erb
<div class="container portfolio-container">
  <%= form_with(model: type_paiment, local: true) do |form| %>
    <% if type_paiment.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(type_paiment.errors.count, "error") %> prohibited this type_paiment from being saved:</h2>

        <ul>
        <% type_paiment.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group col-md-4">
      <%= form.label :Type %>
      <%= form.text_field :name, class:"form-control" %>
    </div>
  <br>
    <div class="form-group">
      <%= form.submit "Valider", class:"btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/type_paiments/edit.html.erb
<div class="container portfolio-container">
  <h1>Editing Type Paiment</h1>

  <%= render 'form', type_paiment: @type_paiment %>

  <%= link_to 'Voir', @type_paiment %> |
  <%= link_to 'Retour', type_paiments_path %>
</div>

app/views/type_paiments/index.html.erb
<div class="container portfolio-container">
  <p id="notice"><%= notice %></p>

  <h1>Type Paiments</h1>

  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @type_paiments.each do |type_paiment| %>
        <tr>
          <td><%= type_paiment.name %></td>
          <td><%= link_to 'Voir', type_paiment %></td>
          <td><%= link_to 'Editer', edit_type_paiment_path(type_paiment) %></td>
          <td><%= link_to 'Supprimer', type_paiment, method: :delete, data: { confirm: 'Êtes-vous sûre?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'Ajouter', new_type_paiment_path %>
</div>

app/views/type_paiments/new.html.erb
<div class="container portfolio-container">
  <h1>Lise des types de paiment</h1>

  <%= render 'form', type_paiment: @type_paiment %>

  <%= link_to 'Retour', type_paiments_path %>
</div>

app/views/type_paiments/show.html.erb
<div class="container portfolio-container">
  <p id="notice"><%= notice %></p>

  <p>
    <strong>Name:</strong>
    <%= @type_paiment.name %>
  </p>

  <%= link_to 'Editer', edit_type_paiment_path(@type_paiment) %> |
  <%= link_to 'Retour', type_paiments_path %>
</div>