config/routes.rb
Rails.application.routes.draw do
  resources :reglements
  resources :actes
  resources :type_paiments
  resources :ipms
  resources :comptabilites do
    member do
      get :print_button
    end
  end
  devise_for :users, path: ''
  #devise_for :users, path: '', path_names: {sign_in: 'Login', sign_out: 'Logout', sign_up: 'Register'}, controllers:{sessions: 'users/sessions'}
  get 'pages/index'
  resources :caisses

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'pages#index'
end

app/controllers/caisses_controller.rb
class CaissesController < ApplicationController
  before_action :set_caiss, only: %i[ show edit update destroy ]

  # GET /caisses or /caisses.json
  def index    
    @caisses = Caisse.all

    @selected_date = Date.today
# This will look for records on the given date between 00:00:00 and 23:59:59
    @caiss_journaliers = Caisse.where(:created_at => @selected_date.beginning_of_day..@selected_date.end_of_day)
  end

  # GET /caisses/1 or /caisses/1.json
  def show
  end

  # GET /caisses/new
  def new
    @caiss = Caisse.new
  end

  # GET /caisses/1/edit
  def edit
  end

  # POST /caisses or /caisses.json
  def create
    @caiss = Caisse.new(caiss_params)

    respond_to do |format|
      if @caiss.save
        format.html { redirect_to @caiss, notice: "Enregistrement effectué avec succés." }
        format.json { render :show, status: :created, location: @caiss }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @caiss.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /caisses/1 or /caisses/1.json
  def update
    respond_to do |format|
      if @caiss.update(caiss_params)
        format.html { redirect_to @caiss, notice: "Modifié avec succés." }
        format.json { render :show, status: :ok, location: @caiss }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @caiss.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /caisses/1 or /caisses/1.json
  def destroy
    @caiss.destroy
    respond_to do |format|
      format.html { redirect_to caisses_url, notice: "Supprimer avec succés." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_caiss
      @caiss = Caisse.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def caiss_params
      params.require(:caisse).permit(:nom, :prenom, :acte, :payement, :montant, :telephone)
    end
end

app/helpers/caisses_helper.rb
module CaissesHelper
end

app/views/caisses/_form.html.erb
<div class="container portfolio-container">
  <%= form_with(model: caiss, local: true) do |form| %>
    <% if caiss.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(caiss.errors.count, "error") %> Impossible de sauvegarder:</h2>

        <ul>
        <% caiss.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group col-md-4">
      <%= form.label :nom %>
      <%= form.text_field :nom, class:"form-control" %>
    </div>

    <div class="form-group col-md-4">
      <%= form.label :prenom %>
      <%= form.text_field :prenom, class:"form-control" %>
    </div>

    <div class="form-group col-md-4">
      <%= form.label :acte %>
      <%= form.text_field :acte, class:"form-control" %>
    </div>

    <div class="form-group col-md-4">
      <%= form.label :payement %>
      <%= form.text_field :payement, class:"form-control" %>
    </div>

    <div class="form-group col-md-4">
      <%= form.label :montant %>
      <%= form.number_field :montant, class:"form-control" %>
    </div>

    <div class="form-group col-md-4">
      <%= form.label :telephone %>
      <%= form.text_field :telephone, class:"form-control" %>
    </div>

    <div class="actions">
      <%= form.submit %>
    </div>
  <% end %>
</div>

app/views/caisses/edit.html.erb
<div class="container portfolio-container">
  <h1>Editer</h1>

  <%= render 'form', caiss: @caiss %>

  <%= link_to 'Voir', @caiss %> |
  <%= link_to 'Retour', caisses_path %>
</div>

app/views/caisses/index.html.erb
<div class="container portfolio-container">
  <p id="notice"><%= notice %></p>

  <h1>Caisse <span> Aujourd'hui: <%= @total= @caiss_journaliers.sum("montant") %> </span -->
  <br></h1>

  <table>
    <thead>
      <tr>
        <th>Nom</th>
        <th>Prenom</th>
        <th>Acte</th>
        <th>Payement</th>
        <th>Montant</th>
        <th>Telephone</th>
        <th>Created_At</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @caisses.each do |caiss| %>
        <tr>
          <td><%= caiss.nom %></td>
          <td><%= caiss.prenom %></td>
          <td><%= caiss.acte %></td>
          <td><%= caiss.payement %></td>
          <td><%= caiss.montant %></td>
          <td><%= caiss.telephone %></td>
          <td><%= caiss.created_at %></td>
          <td><%= link_to 'Voir', caiss %></td>
          <td><%= link_to 'Modifier', edit_caiss_path(caiss) %></td>
          <td><%= link_to 'Supprimer', caiss, method: :delete, data: { confirm: 'Êtes-vous sûre?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <br>
  <hr>
  <br>
  <br>
<div class="row">
  <div class="col-md-5">
    <%= form_tag(method: :get) do %>
      <div class="form-group">
        <%#= label :Selectionner_une_date %>
        <%= date_field_tag(:selected_date, params[:selected_date], class:"form-control col-sm-2") %>
        <br>
      <%= submit_tag ("Rechercher"),  class:"form-control col-md-2 btn-primary" %>
      </div>
      <br>
      <%# if defined?(@query) && @query.present?  %>
        <%#= link_to 'Réinitialiser', ouvriers_path %>
      <%# end %>
    <% end %>
  </div>

  <%= link_to 'Nouveau', new_caiss_path %>
</div>

app/views/caisses/new.html.erb
<div class="container portfolio-container">
  <h1>New Caiss</h1>

  <%= render 'form', caiss: @caiss %>

  <%= link_to 'Back', caisses_path %>
</div>

app/views/caisses/show.html.erb
<div class="container portfolio-container">
  <p id="notice"><%= notice %></p>

  <p>
    <strong>Nom:</strong>
    <%= @caiss.nom %>
  </p>

  <p>
    <strong>Prenom:</strong>
    <%= @caiss.prenom %>
  </p>

  <p>
    <strong>Acte:</strong>
    <%= @caiss.acte %>
  </p>

  <p>
    <strong>Payement:</strong>
    <%= @caiss.payement %>
  </p>

  <p>
    <strong>Montant:</strong>
    <%= @caiss.montant %>
  </p>

  <p>
    <strong>Telephone:</strong>
    <%= @caiss.telephone %>
  </p>

  <%= link_to 'Edit', edit_caiss_path(@caiss) %> |
  <%= link_to 'Back', caisses_path %>