config/routes.rb
Rails.application.routes.draw do
  resources :reglements
  resources :actes
  resources :type_paiments
  resources :ipms
  resources :comptabilites do
    member do
      get :print_button
    end
  end
  devise_for :users, path: ''
  #devise_for :users, path: '', path_names: {sign_in: 'Login', sign_out: 'Logout', sign_up: 'Register'}, controllers:{sessions: 'users/sessions'}
  get 'pages/index'
  resources :caisses

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'pages#index'
end

app/models/acte.rb
class Acte < ApplicationRecord
  has_many :comptabilites
end

app/controllers/actes_controller.rb
class ActesController < ApplicationController
  before_action :set_acte, only: [:show, :edit, :update, :destroy]
  access all: [:index, :show, :new, :edit, :create, :update, :destroy], user: :all

  # GET /actes
  def index
    @actes = Acte.all
  end

  # GET /actes/1
  def show
  end

  # GET /actes/new
  def new
    @acte = Acte.new
  end

  # GET /actes/1/edit
  def edit
  end

  # POST /actes
  def create
    @acte = Acte.new(acte_params)

    if @acte.save
      redirect_to @acte, notice: 'Acte was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /actes/1
  def update
    if @acte.update(acte_params)
      redirect_to @acte, notice: 'Acte was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /actes/1
  def destroy
    @acte.destroy
    redirect_to actes_url, notice: 'Acte was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_acte
      @acte = Acte.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def acte_params
      params.require(:acte).permit(:name)
    end
end

app/helpers/actes_helper.rb
module ActesHelper
end

app/views/actes/_form.html.erb
<div class="container portfolio-container">
  <%= form_with(model: acte, local: true) do |form| %>
    <% if acte.errors.any? %>
      <div id="error_explanation" class="alert alert-danger">
        <h2><%= pluralize(acte.errors.count, "error") %> prohibited this acte from being saved:</h2>

        <ul>
        <% acte.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group col-md-4">
      <%= form.label :name %>
      <%= form.text_field :name, class:"form-control" %>
    </div>
<br>

    <div class="form-group">
      <%= form.submit "Valider", class:"btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/actes/edit.html.erb
<div class="container portfolio-container">
  <h1>Modifier Acte</h1>

  <%= render 'form', acte: @acte %>

  <%= link_to 'Show', @acte %> |
  <%= link_to 'Back', actes_path %>
</div>

app/views/actes/index.html.erb
<div class="container portfolio-container">
  <p id="notice"><%= notice %></p>

  <h1>Liste des Actes</h1>

  <table>
    <thead>
      <tr>
        <th>Libellé</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @actes.each do |acte| %>
        <tr>
          <td><%= acte.name %></td>
          <td><%= link_to 'Voir', acte %></td>
          <td><%= link_to 'Editer', edit_acte_path(acte) %></td>
          <td><%= link_to 'Supprimer', acte, method: :delete, data: { confirm: 'Êtes-vous sûre?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'Ajouter', new_acte_path, class:"btn btn-primary" %>
</div>

app/views/actes/new.html.erb
<div class="container portfolio-container">
  <h1>Nouveau Acte</h1>

  <%= render 'form', acte: @acte %>

  <%= link_to 'Retour', actes_path %>
</div>

app/views/actes/show.html.erb
<div class="container portfolio-container">
  <p id="notice" class="alert alert-success"><%= notice if notice%></p>

  <p>
    <strong>Libellé:</strong>
    <%= @acte.name %>
  </p>

  <%= link_to 'Editer', edit_acte_path(@acte) %> |
  <%= link_to 'Retour', actes_path %>
</div>